site_name: VineCopulaMatlab
repo_url: https://github.com/MalteKurz/VineCopulaMatlab
pages:
- ['index.md', 'Home']

- ['installVineCPP.md', 'Getting started', 'Installation']
- ['DemoVineCPP.md', 'Getting started', 'Demo']
- ['SetSeedVineCPP.md', 'Getting started', 'SetSeedVineCPP']

- ['Functions/PairCopulaAIC.md', 'Functions for pair-copulas', 'PairCopulaAIC']
- ['Functions/PairCopulaCDF.md', 'Functions for pair-copulas', 'PairCopulaCDF']
- ['Functions/PairCopulaFit.md', 'Functions for pair-copulas', 'PairCopulaFit']
- ['Functions/PairCopulaHfun.md', 'Functions for pair-copulas', 'PairCopulaHfun']
- ['Functions/PairCopulaHVolume.md', 'Functions for pair-copulas', 'PairCopulaHVolume']
- ['Functions/PairCopulaIndepTest.md', 'Functions for pair-copulas', 'PairCopulaIndepTest']
- ['Functions/PairCopulaInvHfun.md', 'Functions for pair-copulas', 'PairCopulaInvHfun']
- ['Functions/PairCopulaInvVfun.md', 'Functions for pair-copulas', 'PairCopulaInvVfun']
- ['Functions/PairCopulaKendallTau.md', 'Functions for pair-copulas', 'PairCopulaKendallTau']
- ['Functions/PairCopulaParameterBounds.md', 'Functions for pair-copulas', 'PairCopulaParameterBounds']
- ['Functions/PairCopulaPDF.md', 'Functions for pair-copulas', 'PairCopulaPDF']
- ['Functions/PairCopulaRand.md', 'Functions for pair-copulas', 'PairCopulaRand']
- ['Functions/PairCopulaSelect.md', 'Functions for pair-copulas', 'PairCopulaSelect']
- ['Functions/PairCopulaVfun.md', 'Functions for pair-copulas', 'PairCopulaVfun']
- ['Functions/SetGlobalPairCopulaParameterBounds.md', 'Functions for pair-copulas', 'SetGlobalPairCopulaParameterBounds']

- ['Functions/VineCopulaFit.md', 'Functions for vine copula', 'VineCopulaFit']
- ['Functions/VineCopulaNegLL.md', 'Functions for vine copula', 'VineCopulaNegLL']
- ['Functions/VineCopulaRand.md', 'Functions for vine copula', 'VineCopulaRand']

- ['Functions/VineCopula.md', 'VineCopula class', 'VineCopula class']
- ['Functions/VineCopula_Constructor.md', 'VineCopula class', 'Constructor']
- ['Functions/VineCopula_Fit.md', 'VineCopula class', 'Fit']
- ['Functions/VineCopula_SeqTestOnSimplified.md', 'VineCopula class', 'SeqTestOnSimplified']
- ['Functions/VineCopula_Sim.md', 'VineCopula class', 'Sim']
- ['Functions/VineCopula_StructureSelect.md', 'VineCopula class', 'StructureSelect']


